"""A first AnyInfer call, generated by `anyinfer init`.

Nothing here is special-purpose: it reads the shared configuration file, builds a client
from it, asks one question, and prints the answer. The same file is what the command-line
runner and the OpenAI-compatible sidecar read, so anything proved here works on all three.

    python starter.py
"""

from __future__ import annotations

import sys

import anyinfer as ai

CONFIG_PATH = "anyinfer.json"
"""The configuration `anyinfer init` wrote."""

TARGET = "medium"
"""Where the request goes: a catalog alias, or an explicit 'provider:model'."""

PROMPT = "Say hello in one short sentence."


def run(client: ai.Client, target: str) -> str:
    """Ask one question and return the answer.

    Separate from `main` because this is the part worth keeping: it takes a client and a
    target and knows nothing about where either came from, which is also what makes it
    testable against `anyinfer.testing` without a live provider.
    """
    return client.generate(PROMPT, target=target).text


def main() -> int:
    """Load the configuration, run one request, print the answer."""
    config = ai.load_config(CONFIG_PATH)
    if not config.providers:
        print(
            f"{CONFIG_PATH} configures no providers yet. Start a local engine or set an "
            "API key, then run `anyinfer init --force` again.",
            file=sys.stderr,
        )
        return 1

    with ai.Client(
        list(config.providers),
        route=config.route,
        history=config.history,
        cache=config.cache,
    ) as client:
        try:
            print(run(client, TARGET))
        except ai.AnyInferError as exc:
            # Every library error carries a bounded detail and an actionable hint. A
            # traceback would bury both.
            print(f"error: {exc.detail}", file=sys.stderr)
            if exc.hint:
                print(f"hint: {exc.hint}", file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
