r"""AnyInfer — an inference multiplexer.

Normalized requests in, typed event streams or validated results out, across hosted
providers and local engines, with routing, structured-output contracts, telemetry, and
hardware-aware local inference built in.

Quickstart:

```python
import anyinfer as ai

client = ai.Client([ai.ProviderSettings.of("ollama")])
result = client.generate("Say hello in one sentence.", target="ollama:qwen3:8b")
print(result.text, result.timing.first_token_ms)
```

See the [documentation](https://anyinfer.dev/) for concepts, how-to
guides, and per-provider pages.
"""

from ._client import (
    AsyncClient,
    AsyncStream,
    CatalogEntryFit,
    CatalogView,
    Client,
    MessagesInput,
    ProviderSettings,
    SyncStream,
    Tool,
    tool,
)
from .capabilities import (
    ContextBudget,
    CostEstimate,
    HeuristicTokenEstimator,
    PricingTable,
    RequestEstimate,
    TokenEstimate,
    TokenEstimator,
    build_context_budget,
    check_context_fit,
    estimate_request,
    fetch_pricing,
    load_default_pricing,
)
from .catalog import (
    BEST_AT,
    Catalog,
    ModelEntry,
    ModelVariant,
    OllamaChannel,
    load_default_catalog,
)
from .config import (
    CONFIG_FORMAT_VERSION,
    MAX_CONFIG_BYTES,
    AnyInferConfig,
    load_config,
    loads_config,
)
from .credentials import CredentialResolver, ResolverChain, default_resolver
from .errors import (
    AllTargetsFailedError,
    AnyInferError,
    AuthError,
    ConfigError,
    ContextLengthError,
    CredentialError,
    LocalRuntimeError,
    ModelNotFoundError,
    Phase,
    ProviderError,
    ProviderUnavailableError,
    RateLimitError,
    SchemaViolationError,
    StreamProtocolError,
    ToolLoopError,
    TransportError,
)
from .events import (
    AttemptCompleted,
    AttemptStarted,
    ContextReduced,
    DownloadProgress,
    FallbackTriggered,
    FirstToken,
    Observer,
    ParameterDropped,
    ProviderDiagnostic,
    RepairAttempted,
    RequestCompleted,
    RequestFailed,
    RequestStarted,
    RetryScheduled,
    ServerLifecycle,
    TargetResolved,
    TelemetryEvent,
    UsageEstimated,
)
from .redaction import RedactionRegistry, redact, register_secret
from .registry import (
    HostShorthand,
    ProviderDescriptor,
    ProviderRegistry,
    ProviderSetupSpec,
    SetupField,
    default_registry,
)
from .routing import Retry, Route
from .types import (
    AttemptFailed,
    AttemptRecord,
    ContentPart,
    Diagnostic,
    DiagnosticSeverity,
    DiscoveredModel,
    ErrorInfo,
    Feature,
    FinishReason,
    Generation,
    GenerationRequest,
    Health,
    LocalModelInfo,
    Mechanism,
    Message,
    ModelCapabilities,
    Outcome,
    Pricing,
    Provenance,
    ReasoningDelta,
    ReasoningEffort,
    Repair,
    ResolvedTarget,
    Role,
    Sampling,
    SchemaSpec,
    Sourced,
    StreamEnded,
    StreamEvent,
    SupportsJSONSchema,
    Target,
    Text,
    TextDelta,
    Timing,
    TimingMark,
    TimingMarkName,
    TokenCalibration,
    ToolCall,
    ToolCallDelta,
    ToolChoice,
    ToolResult,
    ToolSpec,
    Usage,
    UsageUpdate,
    assistant,
    system,
    user,
)
from .verification import Verification

__version__ = "0.1.1"

__all__ = [
    "BEST_AT",
    "CONFIG_FORMAT_VERSION",
    "MAX_CONFIG_BYTES",
    "AllTargetsFailedError",
    "AnyInferConfig",
    "AnyInferError",
    "AsyncClient",
    "AsyncStream",
    "AttemptCompleted",
    "AttemptFailed",
    "AttemptRecord",
    "AttemptStarted",
    "AuthError",
    "Catalog",
    "CatalogEntryFit",
    "CatalogView",
    "Client",
    "ConfigError",
    "ContentPart",
    "ContextBudget",
    "ContextLengthError",
    "ContextReduced",
    "CostEstimate",
    "CredentialError",
    "CredentialResolver",
    "Diagnostic",
    "DiagnosticSeverity",
    "DiscoveredModel",
    "DownloadProgress",
    "ErrorInfo",
    "FallbackTriggered",
    "Feature",
    "FinishReason",
    "FirstToken",
    "Generation",
    "GenerationRequest",
    "Health",
    "HeuristicTokenEstimator",
    "HostShorthand",
    "LocalModelInfo",
    "LocalRuntimeError",
    "Mechanism",
    "Message",
    "MessagesInput",
    "ModelCapabilities",
    "ModelEntry",
    "ModelNotFoundError",
    "ModelVariant",
    "Observer",
    "OllamaChannel",
    "Outcome",
    "ParameterDropped",
    "Phase",
    "Pricing",
    "PricingTable",
    "Provenance",
    "ProviderDescriptor",
    "ProviderDiagnostic",
    "ProviderError",
    "ProviderRegistry",
    "ProviderSettings",
    "ProviderSetupSpec",
    "ProviderUnavailableError",
    "RateLimitError",
    "ReasoningDelta",
    "ReasoningEffort",
    "RedactionRegistry",
    "Repair",
    "RepairAttempted",
    "RequestCompleted",
    "RequestEstimate",
    "RequestFailed",
    "RequestStarted",
    "ResolvedTarget",
    "ResolverChain",
    "Retry",
    "RetryScheduled",
    "Role",
    "Route",
    "Sampling",
    "SchemaSpec",
    "SchemaViolationError",
    "ServerLifecycle",
    "SetupField",
    "Sourced",
    "StreamEnded",
    "StreamEvent",
    "StreamProtocolError",
    "SupportsJSONSchema",
    "SyncStream",
    "Target",
    "TargetResolved",
    "TelemetryEvent",
    "Text",
    "TextDelta",
    "Timing",
    "TimingMark",
    "TimingMarkName",
    "TokenCalibration",
    "TokenEstimate",
    "TokenEstimator",
    "Tool",
    "ToolCall",
    "ToolCallDelta",
    "ToolChoice",
    "ToolLoopError",
    "ToolResult",
    "ToolSpec",
    "TransportError",
    "Usage",
    "UsageEstimated",
    "UsageUpdate",
    "Verification",
    "__version__",
    "assistant",
    "build_context_budget",
    "check_context_fit",
    "default_registry",
    "default_resolver",
    "estimate_request",
    "fetch_pricing",
    "load_config",
    "load_default_catalog",
    "load_default_pricing",
    "loads_config",
    "redact",
    "register_secret",
    "system",
    "tool",
    "user",
]
