"""The instruction fragment ``anyinfer agents-md`` prints for a consuming repository.

A coding agent integrating this library from pre-training and a web search will produce an
OpenAI clone — ``client.chat.completions``, a ``model=`` keyword, ``response_format`` —
because that is what nearly every other library in this space looks like. AnyInfer is
deliberately not that, so the most predictable guess is also the most likely to be wrong.
This module renders the short, adversarial correction: the call shape, and the specific
wrong answers worth pre-empting.

Two rules shape everything here, and both come from AGENTS.md:

- **Derived, never authored twice.** The provider counts come from the registry, the
  extras from installed distribution metadata, and the version from the package. A
  fragment generated by one release says what that release actually offers, and a second
  hand-written description of the API cannot drift from the first because there is not
  one.
- **No internal shorthand.** This text is read in somebody else's repository, where a
  decision-record number explains nothing to anybody. Rules are stated in plain words,
  and a test sweeps every rendered format for the pattern.

Nothing here is loaded, sent, or interpolated at request time. It is a file a human pipes
into their own instructions.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from .config import AnyInferConfig
    from .registry import ProviderRegistry

__all__ = [
    "AGENTS_MD_FORMATS",
    "AgentsMdFormat",
    "installed_extras",
    "render_agents_md",
]

AgentsMdFormat = Literal["agents", "claude", "copilot"]
"""Which consuming file the fragment is shaped for.

The body is identical in all three — one description of one API, and only the wrapper
differs, because the three tools disagree about where instructions live and what a file
opens with, not about what is true.
"""

AGENTS_MD_FORMATS = ("agents", "claude", "copilot")
"""Accepted `AgentsMdFormat` values, in the order ``--format`` lists them."""

_HEADINGS: dict[str, str] = {
    "agents": "## Using AnyInfer",
    "claude": "# Working with AnyInfer",
    "copilot": "# Working with AnyInfer",
}

_PREAMBLE: dict[str, str] = {
    "agents": "",
    "claude": "",
    "copilot": (
        "These instructions apply to any change in this repository that calls AnyInfer.\n\n"
    ),
}


def render_agents_md(
    *,
    style: AgentsMdFormat = "agents",
    registry: ProviderRegistry | None = None,
    config: AnyInferConfig | None = None,
    version: str | None = None,
) -> str:
    """Render the instruction fragment for a consuming repository.

    Args:
        style: Which consuming file to shape the wrapper for; see `AgentsMdFormat`.
        registry: Registry to introspect for provider counts. Defaults to the
            process-wide one, so an installed third-party provider is counted too.
        config: A loaded configuration, when the caller passed ``--config``. Its
            configured instances and default route are named, so an agent working in that
            repository writes targets that exist there.
        version: Version to stamp; defaults to the installed package's.

    Returns:
        Markdown text, ending in a newline.
    """
    from . import __version__, default_registry

    active = registry if registry is not None else default_registry
    stamp = version or __version__

    lines: list[str] = []
    preamble = _PREAMBLE[style]
    if preamble:
        lines.append(preamble.rstrip("\n"))
        lines.append("")
    lines.append(_HEADINGS[style])
    lines.append("")
    lines.append(
        f"Generated by `anyinfer agents-md` from AnyInfer {stamp}. Regenerate it after "
        "upgrading; what follows describes that version and nothing later."
    )
    lines.append("")
    lines.extend(_shape())
    lines.append("")
    lines.extend(_traps())
    lines.append("")
    lines.extend(_never_hand_roll())
    lines.append("")
    if config is not None:
        lines.extend(_configured(config))
        lines.append("")
    lines.extend(_where_to_look(active))
    return "\n".join(lines).rstrip("\n") + "\n"


def _shape() -> list[str]:
    """The call skeleton, which is the one thing worth copying verbatim."""
    return [
        "### The shape of a call",
        "",
        "```python",
        "import anyinfer as ai",
        "",
        "client = ai.Client([",
        '    ai.ProviderSettings.of("anthropic", api_key="env://ANTHROPIC_API_KEY"),',
        '    ai.ProviderSettings.of("ollama"),',
        "])",
        "",
        "result = client.generate(",
        '    "Summarize this:\\n" + text,',
        '    target="anthropic:claude-sonnet-4-5",   # provider:model, or a catalog alias',
        "    schema=schema,                          # optional; validated before you see it",
        "    route=ai.Route(                         # optional; the router owns fallback",
        '        targets=("anthropic:claude-sonnet-4-5", "ollama:qwen3:8b"),',
        "        retry=ai.Retry(max_attempts=2),",
        "    ),",
        ")",
        "print(result.text)",
        "client.close()   # or use the client as a context manager",
        "```",
        "",
        "`AsyncClient` is the same surface with `await`, and `client.stream(...)` yields "
        "typed events. Non-streaming is the drained stream, not a second code path.",
    ]


def _traps() -> list[str]:
    """The predictable wrong guesses, each paired with what the API actually is."""
    rows = [
        (
            '`model="claude-sonnet-4-5"`',
            '`target="anthropic:claude-sonnet-4-5"` — provider-qualified, split on the '
            "first colon only, so a model id may itself contain colons "
            "(`ollama:qwen3:8b`)",
        ),
        (
            '`response_format={"type": "json_object"}`',
            "`schema=` on the request. The strongest mechanism the target supports is "
            "chosen for you, and the reply is validated client-side before it is returned",
        ),
        (
            "`client.chat.completions.create(...)`",
            "`client.generate(...)` / `client.stream(...)` / `client.run_tools(...)`. "
            "There is no OpenAI-shaped namespace; the OpenAI dialect is one edge format",
        ),
        (
            "a retry loop wrapped around the call",
            "`ai.Route` and `ai.Retry`. Retry, fallback, health gating, and repair are the "
            "router's, and a wrapper around the call double-counts every one of them",
        ),
        (
            "`float(result.usage.cost_usd)`",
            "a `Decimal`, and `None` means *unknown* rather than zero. Treating unknown "
            "as free is the one arithmetic mistake this library refuses to make",
        ),
        (
            "`capabilities.context_window > 8000`",
            "`capabilities.context_window` is a `Sourced[int]`: `.value` with a "
            "`.provenance` of `catalog`, `discovered`, `probed`, or `default`. An "
            "estimated window is never presented as an authoritative one",
        ),
        (
            "`pip install anyinfer[anthropic]`",
            "no such extra. Hosted adapters are core; extras exist only where a real "
            "dependency does",
        ),
    ]
    lines = [
        "### What not to guess",
        "",
        "| A plausible guess | What the API actually is |",
        "|---|---|",
    ]
    lines.extend(f"| {guess} | {actual} |" for guess, actual in rows)
    return lines


def _never_hand_roll() -> list[str]:
    """The boundary: what belongs to the library rather than to the integration."""
    return [
        "### Do not hand-roll these",
        "",
        "Each one already exists in the core, is tested there, and reports what it did:",
        "",
        "- **Retry, backoff, and fallback** — `ai.Route`, `ai.Retry`. `Retry-After` is "
        "honoured, and every attempt lands on `result.attempts`.",
        "- **Schema validation and repair** — pass `schema=` and, if you want repair, "
        "`repair=ai.Repair(max_attempts=1)`.",
        '- **Provider branches** — no `if provider == "ollama"`. Providers are '
        "described by registry descriptors; anything a caller needs to know is a field on "
        "one.",
        "- **Token counting and cost arithmetic** — `client.budget(...)` before a call, "
        "`result.usage` after it.",
        "- **Trimming a prompt to fit** — `anyinfer.context` reduces a corpus and reports "
        "exactly what it omitted; `ai.HistoryPolicy` compacts a conversation.",
        '- **Secret handling** — pass `api_key="env://VAR"`. Resolved values are '
        "registered for redaction, so they cannot reach a log line, an error, or an event.",
    ]


def _configured(config: AnyInferConfig) -> list[str]:
    """Name what this repository actually configured, so targets written here exist."""
    lines = ["### This repository's configuration", ""]
    if not config.providers:
        lines.append(
            "The configuration file names no providers yet. Run `anyinfer init` to write "
            "one from what the machine can already use."
        )
        return lines
    lines.append("Configured provider instances:")
    lines.append("")
    for settings in config.providers:
        engine = settings.provider_id
        label = (
            f"`{settings.instance_id}`"
            if settings.instance_id == engine
            else f"`{settings.instance_id}` (the `{engine}` adapter)"
        )
        lines.append(f"- {label}")
    if config.route is not None:
        targets = ", ".join(f"`{target}`" for target in config.route.targets)
        lines.append("")
        lines.append(
            f"Default route, tried in order: {targets}. A call that names no target uses it."
        )
    return lines


def installed_extras() -> tuple[str, ...]:
    """The extras this distribution actually declares, minus the contributor-only one.

    Read from installed metadata rather than listed here, because a hand-copied list is
    how a fragment ends up recommending ``pip install anyinfer[anthropic]`` — an extra
    that has never existed. An uninstalled source checkout has no metadata to read and
    honestly reports nothing.
    """
    from importlib.metadata import PackageNotFoundError, metadata

    try:
        declared = metadata("anyinfer").get_all("Provides-Extra") or []
    except PackageNotFoundError:
        return ()
    return tuple(name for name in declared if name != "dev")


def _where_to_look(registry: ProviderRegistry) -> list[str]:
    """Counts read from the registry, and the commands that answer the rest."""
    from .providers.presets import COMPAT_PRESETS

    preset_ids = {preset.id for preset in COMPAT_PRESETS}
    known = registry.known_ids()
    dedicated = [pid for pid in known if pid not in preset_ids]
    extras = installed_extras()
    lines = [
        "### Where to check rather than guess",
        "",
        f"{len(known)} providers are registered here: {len(dedicated)} dedicated adapters "
        f"and {len(known) - len(dedicated)} declarative OpenAI-compatible presets.",
        "",
    ]
    if extras:
        lines.append(
            "Extras this installation declares: "
            + ", ".join(f"`{name}`" for name in extras)
            + ". There is no per-provider extra for a hosted API."
        )
        lines.append("")
    lines.extend(
        [
            "- `anyinfer providers` — every provider and the fields it needs.",
            "- `anyinfer verify <target>` — proves a target answers, which a health check "
            "cannot: a credential can be valid for a model listing and useless for inference.",
            '- `anyinfer run "..." --dry-run` — what a request would cost and whether it fits.',
            "- `anyinfer init` — writes a working configuration from what this machine has.",
            "- <https://anyinfer.dev/llms.txt> — the documentation index, for agents.",
        ]
    )
    return lines
