"""The starter program ``anyinfer init`` writes beside the configuration it generates.

The template is a *complete, valid Python file* rather than a format string with holes in
it, and generation is a two-line substitution over it. That is the only arrangement in
which the thing shipped and the thing generated cannot diverge: the checked-in example at
``docs/examples/starter.py`` is this template rendered with its own defaults, and a test
asserts the two are byte-identical. A template assembled from fragments in ``cli.py``
would be unrunnable until someone ran the command, which is how a generator ends up
emitting a program with a syntax error in it.

The rendered file is not a demo of everything this library does. It is the shortest
program that proves the configuration works, which is what the first five minutes need.
"""

from __future__ import annotations

__all__ = [
    "DEFAULT_STARTER_CONFIG",
    "DEFAULT_STARTER_TARGET",
    "STARTER_TEMPLATE",
    "render_starter",
]

DEFAULT_STARTER_CONFIG = "anyinfer.json"
"""Configuration path the checked-in example reads, and `init`'s own default output."""

DEFAULT_STARTER_TARGET = "medium"
"""Target the checked-in example points at.

A catalog alias rather than a concrete ``provider:model``: the example has to name
*something*, and an alias is the one spelling that is not a claim about which engine a
reader has installed.
"""

STARTER_TEMPLATE = '''"""A first AnyInfer call, generated by `anyinfer init`.

Nothing here is special-purpose: it reads the shared configuration file, builds a client
from it, asks one question, and prints the answer. The same file is what the command-line
runner and the OpenAI-compatible sidecar read, so anything proved here works on all three.

    python starter.py
"""

from __future__ import annotations

import sys

import anyinfer as ai

CONFIG_PATH = "anyinfer.json"
"""The configuration `anyinfer init` wrote."""

TARGET = "medium"
"""Where the request goes: a catalog alias, or an explicit 'provider:model'."""

PROMPT = "Say hello in one short sentence."


def run(client: ai.Client, target: str) -> str:
    """Ask one question and return the answer.

    Separate from `main` because this is the part worth keeping: it takes a client and a
    target and knows nothing about where either came from, which is also what makes it
    testable against `anyinfer.testing` without a live provider.
    """
    return client.generate(PROMPT, target=target).text


def main() -> int:
    """Load the configuration, run one request, print the answer."""
    config = ai.load_config(CONFIG_PATH)
    if not config.providers:
        print(
            f"{CONFIG_PATH} configures no providers yet. Start a local engine or set an "
            "API key, then run `anyinfer init --force` again.",
            file=sys.stderr,
        )
        return 1

    with ai.Client(
        list(config.providers),
        route=config.route,
        history=config.history,
        cache=config.cache,
    ) as client:
        try:
            print(run(client, TARGET))
        except ai.AnyInferError as exc:
            # Every library error carries a bounded detail and an actionable hint. A
            # traceback would bury both.
            print(f"error: {exc.detail}", file=sys.stderr)
            if exc.hint:
                print(f"hint: {exc.hint}", file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''
"""The example, verbatim. `render_starter` substitutes the two lines that vary."""


def render_starter(*, target: str, config_path: str) -> str:
    """Render the starter program for one target and configuration path.

    Args:
        target: What to put in the generated ``TARGET`` line — an alias or a
            ``provider:model``.
        config_path: What to put in the generated ``CONFIG_PATH`` line.

    Returns:
        Python source, byte-identical to `STARTER_TEMPLATE` apart from those two lines.

    Raises:
        ValueError: If either value contains a quote or newline. Both are interpolated
            into a Python string literal, and a generator that emits a file which will not
            parse is worse than one that refuses.
    """
    for name, value in (("target", target), ("config path", config_path)):
        if not value or any(character in value for character in '"\\\n\r'):
            raise ValueError(f"a starter {name} cannot be empty or contain quotes")
    return STARTER_TEMPLATE.replace(
        f'CONFIG_PATH = "{DEFAULT_STARTER_CONFIG}"', f'CONFIG_PATH = "{config_path}"', 1
    ).replace(f'TARGET = "{DEFAULT_STARTER_TARGET}"', f'TARGET = "{target}"', 1)
