"""Generate the link-preview (Open Graph) card from the canonical wordmark.

Social platforms rasterize nothing: `og:image` has to be a real PNG, and it has to be
1200x630 or it gets cropped unpredictably. Rather than hand-draw a second piece of brand
art that would drift from `docs/assets/`, this script composes the card out of the
canonical dark wordmark -- the same paths, unmodified -- on the brand's deep-teal surface,
and writes both the SVG source and the rasterized PNG into `docs/assets/`.

Run it after any wordmark change::

    python scripts/render_social_card.py

The SVG half is pure string composition and is asserted against the committed file by
tests/test_branding.py, so a stale card fails the suite. The PNG half needs PySide6's SVG
renderer (a dev dependency, already used for the demo bundle icon); without it the script
refreshes the SVG and says what it skipped.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "docs" / "assets"
WORDMARK = ASSETS / "anyinfer-horizontal-dark.svg"
CARD_SVG = ASSETS / "anyinfer-social-card.svg"
CARD_PNG = ASSETS / "anyinfer-social-card.png"

# Facebook/LinkedIn/Slack/X all render a 1.91:1 summary image; 1200x630 is the size every
# one of them accepts without re-cropping.
WIDTH, HEIGHT = 1200, 630
# The wordmark occupies roughly two thirds of the card width, which keeps the mark legible
# at the ~250px wide thumbnail chat clients actually show.
MARK_WIDTH = 760.0
BACKGROUND = "#0B3B3C"  # --anyinfer-teal-deep

# Inked extent of the wordmark in its own user units, which is *not* its viewBox: the
# canonical file carries ~34 units of right padding, so centring on the viewBox would push
# the mark visibly left of centre. Measured from the art itself -- `main()` re-measures on
# every run and fails if a wordmark edit moves these, so the constant cannot go stale.
MARK_CONTENT_BOX = (2.2, 22.0, 311.8, 60.0)


def _wordmark_body() -> tuple[str, tuple[float, float, float, float]]:
    """Return the wordmark's inner markup and its viewBox, straight from the canonical file."""
    source = WORDMARK.read_text(encoding="utf-8")
    view_box = re.search(r'viewBox="([-\d. ]+)"', source)
    if view_box is None:
        raise ValueError(f"{WORDMARK.name} has no viewBox to place the mark against")
    numbers = tuple(float(value) for value in view_box.group(1).split())
    if len(numbers) != 4:
        raise ValueError(f"{WORDMARK.name} has a malformed viewBox")
    body = source.split(">", 1)[1].rsplit("</svg>", 1)[0].strip("\n")
    min_x, min_y, box_width, box_height = numbers
    return body, (min_x, min_y, box_width, box_height)


def render_card_svg() -> str:
    """Compose the card SVG. Deterministic: same wordmark in, same bytes out."""
    body, _ = _wordmark_body()
    ink_x, ink_y, ink_width, ink_height = MARK_CONTENT_BOX
    scale = MARK_WIDTH / ink_width
    # Centre the inked mark horizontally, and a touch above centre vertically so the accent
    # band along the bottom edge does not read as crowding it.
    left = (WIDTH - MARK_WIDTH) / 2
    top = (HEIGHT - ink_height * scale) / 2 - 14
    translate_x = left - ink_x * scale
    translate_y = top - ink_y * scale
    indented = "\n".join(
        f"    {line.strip()}" if line.strip() else "" for line in body.splitlines()
    )
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" \
viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-label="AnyInfer">
  <!-- Generated by scripts/render_social_card.py from anyinfer-horizontal-dark.svg. -->
  <defs>
    <radialGradient id="glow" cx="0.5" cy="0.42" r="0.75">
      <stop offset="0" stop-color="#2C7A6F" stop-opacity="0.45"></stop>
      <stop offset="1" stop-color="#2C7A6F" stop-opacity="0"></stop>
    </radialGradient>
    <linearGradient id="band" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#2C7A6F"></stop>
      <stop offset="0.55" stop-color="#E8963C"></stop>
      <stop offset="1" stop-color="#F0C86A"></stop>
    </linearGradient>
  </defs>
  <rect width="{WIDTH}" height="{HEIGHT}" fill="{BACKGROUND}"></rect>
  <rect width="{WIDTH}" height="{HEIGHT}" fill="url(#glow)"></rect>
  <g transform="translate({translate_x:.2f} {translate_y:.2f}) scale({scale:.5f})">
{indented}
  </g>
  <rect x="0" y="{HEIGHT - 14}" width="{WIDTH}" height="14" fill="url(#band)"></rect>
</svg>
"""


def _draw(svg: str, width: int, height: int) -> Any:
    """Rasterize arbitrary SVG markup to a transparent ARGB image of the given size."""
    from PySide6.QtCore import QByteArray
    from PySide6.QtGui import QImage, QPainter
    from PySide6.QtSvg import QSvgRenderer

    image = QImage(width, height, QImage.Format.Format_ARGB32)
    image.fill(0)
    painter = QPainter(image)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing, True)
    QSvgRenderer(QByteArray(svg.encode("utf-8"))).render(painter)
    painter.end()
    return image


def _measured_content_box() -> tuple[float, float, float, float]:
    """Measure the wordmark's inked extent, in wordmark user units, from its own pixels."""
    _, (min_x, min_y, box_width, box_height) = _wordmark_body()
    zoom = 10  # 10 device pixels per user unit: finer than the 0.1-unit tolerance below.
    image = _draw(
        WORDMARK.read_text(encoding="utf-8"), round(box_width * zoom), round(box_height * zoom)
    )
    # Format_ARGB32 is BGRA in memory, so every fourth byte from offset 3 is an alpha value.
    pixels, stride = bytes(image.constBits()), image.bytesPerLine()
    alpha = [pixels[y * stride + 3 : (y + 1) * stride : 4] for y in range(image.height())]
    inked = [(y, row) for y, row in enumerate(alpha) if row.strip(b"\x00")]
    if not inked:
        raise ValueError(f"{WORDMARK.name} rendered to nothing")
    left = min(len(row) - len(row.lstrip(b"\x00")) for _, row in inked)
    right = max(len(row.rstrip(b"\x00")) for _, row in inked)
    return (
        left / zoom + min_x,
        inked[0][0] / zoom + min_y,
        (right - left) / zoom,
        (inked[-1][0] + 1 - inked[0][0]) / zoom,
    )


def main() -> int:
    """Rewrite both card files, refusing to publish a card the wordmark has outgrown."""
    svg = render_card_svg()
    CARD_SVG.write_text(svg, encoding="utf-8", newline="\n")
    print(f"wrote {CARD_SVG.relative_to(ROOT)}")

    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    try:
        from PySide6.QtGui import QGuiApplication
    except ImportError:
        print("PySide6 is not installed - the PNG card was left untouched")
        return 0

    application = QGuiApplication.instance() or QGuiApplication([])
    try:
        measured = _measured_content_box()
        if any(abs(a - b) > 0.1 for a, b in zip(measured, MARK_CONTENT_BOX, strict=True)):
            print(
                f"the wordmark's inked extent moved to {measured} - update MARK_CONTENT_BOX "
                f"in {Path(__file__).name} and re-run, or the card will sit off-centre",
                file=sys.stderr,
            )
            return 1
        # No explicit format: Qt picks PNG from the suffix, and the overloads disagree
        # between the runtime (str) and the type stubs (bytes) on how to spell it.
        if not _draw(svg, WIDTH, HEIGHT).save(str(CARD_PNG)):
            raise RuntimeError(f"could not write {CARD_PNG}")
    finally:
        del application
    print(f"wrote {CARD_PNG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
