"""Telemetry events, observers, and secret redaction."""

from ..redaction import (
    REDACTED,
    RedactionRegistry,
    redact,
    register_secret,
)
from .observers import EventDispatcher, Observer, Subscription
from .sinks import JsonlObserver, LoggingObserver, event_to_dict
from .telemetry import (
    PAYLOAD_FIELDS,
    ArenaCompleted,
    AttemptCompleted,
    AttemptStarted,
    CachePlanned,
    ContextReduced,
    CredentialRotated,
    DownloadProgress,
    FallbackTriggered,
    FirstToken,
    ParameterDropped,
    ProviderDiagnostic,
    RateLimitObserved,
    RateLimitWaited,
    RepairAttempted,
    RequestCompleted,
    RequestFailed,
    RequestStarted,
    RetryScheduled,
    ServerLifecycle,
    TargetResolved,
    TelemetryEvent,
    UsageEstimated,
    strip_payloads,
)

__all__ = [
    "PAYLOAD_FIELDS",
    "REDACTED",
    "ArenaCompleted",
    "AttemptCompleted",
    "AttemptStarted",
    "CachePlanned",
    "ContextReduced",
    "CredentialRotated",
    "DownloadProgress",
    "EventDispatcher",
    "FallbackTriggered",
    "FirstToken",
    "JsonlObserver",
    "LoggingObserver",
    "Observer",
    "ParameterDropped",
    "ProviderDiagnostic",
    "RateLimitObserved",
    "RateLimitWaited",
    "RedactionRegistry",
    "RepairAttempted",
    "RequestCompleted",
    "RequestFailed",
    "RequestStarted",
    "RetryScheduled",
    "ServerLifecycle",
    "Subscription",
    "TargetResolved",
    "TelemetryEvent",
    "UsageEstimated",
    "event_to_dict",
    "redact",
    "register_secret",
    "strip_payloads",
]
